const data = {
    'en': {
      'keys-row-1': [
        {'key': '`', 'classes': ['key-square', 'key'], 'data': 'Backquote'}, 
        {'key': '1', 'classes': ['key-square', 'key'], 'data': 'Digit1'}, 
        {'key': '2', 'classes': ['key-square', 'key'], 'data': 'Digit2'}, 
        {'key': '3', 'classes': ['key-square', 'key'], 'data': 'Digit3'}, 
        {'key': '4', 'classes': ['key-square', 'key'], 'data': 'Digit4'}, 
        {'key': '5', 'classes': ['key-square', 'key'], 'data': 'Digit5'}, 
        {'key': '6', 'classes': ['key-square', 'key'], 'data': 'Digit6'}, 
        {'key': '7', 'classes': ['key-square', 'key'], 'data': 'Digit7'}, 
        {'key': '8', 'classes': ['key-square', 'key'], 'data': 'Digit8'}, 
        {'key': '9', 'classes': ['key-square', 'key'], 'data': 'Digit9'}, 
        {'key': '0', 'classes': ['key-square', 'key'], 'data': 'Digit0'}, 
        {'key': '-', 'classes': ['key-square', 'key'], 'data': 'Minus'},
        {'key': '=', 'classes': ['key-square', 'key'], 'data': 'Equal'},
        {'key': 'backspace', 'classes': ['key-special', 'key', 'backspace'], 'data': 'Backspace'},],
    'keys-row-2': [
      {'key': 'tab', 'classes': ['key-special', 'key', 'tab'], 'data': 'Tab'}, 
      {'key': 'q', 'classes': ['key-square', 'key'], 'data': 'KeyQ'}, 
      {'key': 'w', 'classes': ['key-square', 'key'], 'data': 'Keyw'}, 
      {'key': 'e', 'classes': ['key-square', 'key'], 'data': 'KeyE'}, 
      {'key': 'r', 'classes': ['key-square', 'key'], 'data': 'KeyR'}, 
      {'key': 't', 'classes': ['key-square', 'key'], 'data': 'KeyT'}, 
      {'key': 'y', 'classes': ['key-square', 'key'], 'data': 'KeyY'}, 
      {'key': 'u', 'classes': ['key-square', 'key'], 'data': 'KeyU'}, 
      {'key': 'i', 'classes': ['key-square', 'key'], 'data': 'KeyI'}, 
      {'key': 'o', 'classes': ['key-square', 'key'], 'data': 'KeyO'}, 
      {'key': 'p', 'classes': ['key-square', 'key'], 'data': 'KeyP'}, 
      {'key': '[', 'classes': ['key-square', 'key'], 'data': 'BracketLeft'},
      {'key': ']', 'classes': ['key-square', 'key'], 'data': 'BracketRight'},
      {'key': '&#92;', 'classes': ['key-square', 'key'], 'data': 'Backslash'},
      {'key': 'del', 'classes': ['key-special', 'key', 'del'], 'data': 'Delete'},
    ],
    'keys-row-3': [
      {'key': 'capslock', 'classes': ['key-special', 'key', 'capslock'], 'data': 'CapsLock'}, 
      {'key': 'a', 'classes': ['key-square', 'key'], 'data': 'KeyA'}, 
      {'key': 's', 'classes': ['key-square', 'key'], 'data': 'KeyS'}, 
      {'key': 'd', 'classes': ['key-square', 'key'], 'data': 'KeyD'}, 
      {'key': 'f', 'classes': ['key-square', 'key'], 'data': 'KeyF'}, 
      {'key': 'g', 'classes': ['key-square', 'key'], 'data': 'KeyG'}, 
      {'key': 'h', 'classes': ['key-square', 'key'], 'data': 'KeyH'}, 
      {'key': 'j', 'classes': ['key-square', 'key'], 'data': 'KeyJ'}, 
      {'key': 'k', 'classes': ['key-square', 'key'], 'data': 'KeyK'}, 
      {'key': 'l', 'classes': ['key-square', 'key'], 'data': 'KeyL'}, 
      {'key': ';', 'classes': ['key-square', 'key'], 'data': 'Semicolon'}, 
      {'key': '\'', 'classes': ['key-square', 'key'], 'data': 'Quote'},
      {'key': 'enter', 'classes': ['key-special', 'key', 'enter'], 'data': 'Enter'}, 
    ],
    'keys-row-4': [
      {'key': 'shift', 'classes': ['key-special', 'key', 'shift-1'], 'data': 'ShiftLeft'}, 
      {'key': 'z', 'classes': ['key-square', 'key'], 'data': 'KeyZ'}, 
      {'key': 'x', 'classes': ['key-square', 'key'], 'data': 'KeyX'}, 
      {'key': 'c', 'classes': ['key-square', 'key'], 'data': 'KeyC'}, 
      {'key': 'v', 'classes': ['key-square', 'key'], 'data': 'KeyV'}, 
      {'key': 'b', 'classes': ['key-square', 'key'], 'data': 'KeyB'}, 
      {'key': 'n', 'classes': ['key-square', 'key'], 'data': 'KeyN'}, 
      {'key': 'm', 'classes': ['key-square', 'key'], 'data': 'KeyM'}, 
      {'key': ',', 'classes': ['key-square', 'key'], 'data': 'Comma'}, 
      {'key': '.', 'classes': ['key-square', 'key'], 'data': 'Period'}, 
      {'key': '/', 'classes': ['key-square', 'key'], 'data': 'Slash'},
      {'key': '&#708', 'classes': ['key-square', 'key', 'key-special'], 'data': 'ArrowUp'},
      {'key': 'shift', 'classes': ['key-special', 'key', 'shift-2'], 'data': 'ShiftRight'}, 
    ],
    'keys-row-5': [
      {'key': 'ctrl', 'classes': ['key-square', 'key', 'ctrl', 'key-special'], 'data': 'ControlLeft'}, 
      {'key': 'win', 'classes': ['key-square', 'key', 'win', 'key-special'], 'data': 'MetaLeft'},
      {'key': 'alt', 'classes': ['key-square', 'key', 'alt', 'key-special'], 'data': 'AltLeft'},
      {'key': '', 'classes': ['key', 'space', 'key-special'], 'data': 'Space'},
      {'key': 'alt', 'classes': ['key-square', 'key', 'alt', 'key-special'], 'data': 'AltRight'},
      {'key': '&#706', 'classes': ['key-square', 'key', 'key-special'], 'data': 'ArrowLeft'},
      {'key': '&#709', 'classes': ['key-square', 'key', 'key-special'], 'data': 'ArrowDown'},
      {'key': '&#707', 'classes': ['key-square', 'key', 'key-special'], 'data': 'ArrowRight'},
      {'key': 'ctrl', 'classes': ['key-square', 'key', 'ctrl', 'key-special'], 'data': 'ControlRight'}
    ]
    },
    'ru': {
      'keys-row-1': [
        {'key': 'ё', 'classes': ['key-square', 'key'], 'data': 'Backquote'}, 
        {'key': '1', 'classes': ['key-square', 'key'], 'data': 'Digit1'}, 
        {'key': '2', 'classes': ['key-square', 'key'], 'data': 'Digit2'}, 
        {'key': '3', 'classes': ['key-square', 'key'], 'data': 'Digit3'}, 
        {'key': '4', 'classes': ['key-square', 'key'], 'data': 'Digit4'}, 
        {'key': '5', 'classes': ['key-square', 'key'], 'data': 'Digit5'}, 
        {'key': '6', 'classes': ['key-square', 'key'], 'data': 'Digit6'}, 
        {'key': '7', 'classes': ['key-square', 'key'], 'data': 'Digit7'}, 
        {'key': '8', 'classes': ['key-square', 'key'], 'data': 'Digit8'}, 
        {'key': '9', 'classes': ['key-square', 'key'], 'data': 'Digit9'}, 
        {'key': '0', 'classes': ['key-square', 'key'], 'data': 'Digit0'}, 
        {'key': '-', 'classes': ['key-square', 'key'], 'data': 'Minus'},
        {'key': '=', 'classes': ['key-square', 'key'], 'data': 'Equal'},
        {'key': 'backspace', 'classes': ['key-special', 'key', 'backspace'], 'data': 'Backspace'},],
    'keys-row-2': [
      {'key': 'tab', 'classes': ['key-special', 'key', 'tab'], 'data': 'Tab'}, 
      {'key': 'й', 'classes': ['key-square', 'key'], 'data': 'KeyQ'}, 
      {'key': 'ц', 'classes': ['key-square', 'key'], 'data': 'Keyw'}, 
      {'key': 'у', 'classes': ['key-square', 'key'], 'data': 'KeyE'}, 
      {'key': 'к', 'classes': ['key-square', 'key'], 'data': 'KeyR'}, 
      {'key': 'е', 'classes': ['key-square', 'key'], 'data': 'KeyT'}, 
      {'key': 'н', 'classes': ['key-square', 'key'], 'data': 'KeyY'}, 
      {'key': 'г', 'classes': ['key-square', 'key'], 'data': 'KeyU'}, 
      {'key': 'ш', 'classes': ['key-square', 'key'], 'data': 'KeyI'}, 
      {'key': 'щ', 'classes': ['key-square', 'key'], 'data': 'KeyO'}, 
      {'key': 'з', 'classes': ['key-square', 'key'], 'data': 'KeyP'}, 
      {'key': 'х', 'classes': ['key-square', 'key'], 'data': 'BracketLeft'},
      {'key': 'ъ', 'classes': ['key-square', 'key'], 'data': 'BracketRight'},
      {'key': '&#92;', 'classes': ['key-square', 'key'], 'data': 'Backslash'},
      {'key': 'del', 'classes': ['key-special', 'key', 'del'], 'data': 'Delete'},
    ],
    'keys-row-3': [
      {'key': 'capslock', 'classes': ['key-special', 'key', 'capslock'], 'data': 'CapsLock'}, 
      {'key': 'ф', 'classes': ['key-square', 'key'], 'data': 'KeyA'}, 
      {'key': 'ы', 'classes': ['key-square', 'key'], 'data': 'KeyS'}, 
      {'key': 'в', 'classes': ['key-square', 'key'], 'data': 'KeyD'}, 
      {'key': 'а', 'classes': ['key-square', 'key'], 'data': 'KeyF'}, 
      {'key': 'п', 'classes': ['key-square', 'key'], 'data': 'KeyG'}, 
      {'key': 'р', 'classes': ['key-square', 'key'], 'data': 'KeyH'}, 
      {'key': 'о', 'classes': ['key-square', 'key'], 'data': 'KeyJ'}, 
      {'key': 'л', 'classes': ['key-square', 'key'], 'data': 'KeyK'}, 
      {'key': 'д', 'classes': ['key-square', 'key'], 'data': 'KeyL'}, 
      {'key': 'ж', 'classes': ['key-square', 'key'], 'data': 'Semicolon'}, 
      {'key': 'э', 'classes': ['key-square', 'key'], 'data': 'Quote'},
      {'key': 'enter', 'classes': ['key-special', 'key', 'enter'], 'data': 'Enter'}, 
    ],
    'keys-row-4': [
      {'key': 'shift', 'classes': ['key-special', 'key', 'shift-1'], 'data': 'ShiftLeft'}, 
      {'key': 'я', 'classes': ['key-square', 'key'], 'data': 'KeyZ'}, 
      {'key': 'ч', 'classes': ['key-square', 'key'], 'data': 'KeyX'}, 
      {'key': 'с', 'classes': ['key-square', 'key'], 'data': 'KeyC'}, 
      {'key': 'м', 'classes': ['key-square', 'key'], 'data': 'KeyV'}, 
      {'key': 'и', 'classes': ['key-square', 'key'], 'data': 'KeyB'}, 
      {'key': 'т', 'classes': ['key-square', 'key'], 'data': 'KeyN'}, 
      {'key': 'ь', 'classes': ['key-square', 'key'], 'data': 'KeyM'}, 
      {'key': 'б', 'classes': ['key-square', 'key'], 'data': 'Comma'}, 
      {'key': 'ю', 'classes': ['key-square', 'key'], 'data': 'Period'}, 
      {'key': '.', 'classes': ['key-square', 'key'], 'data': 'Slash'},
      {'key': '&#708', 'classes': ['key-square', 'key', 'key-special'], 'data': 'ArrowUp'},
      {'key': 'shift', 'classes': ['key-special', 'key', 'shift-2'], 'data': 'ShiftRight'}, 
    ],
    'keys-row-5': [
      {'key': 'ctrl', 'classes': ['key-square', 'key', 'ctrl', 'key-special'], 'data': 'ControlLeft'}, 
      {'key': 'win', 'classes': ['key-square', 'key', 'win', 'key-special'], 'data': 'MetaLeft'},
      {'key': 'alt', 'classes': ['key-square', 'key', 'alt', 'key-special'], 'data': 'AltLeft'},
      {'key': '', 'classes': ['key', 'space', 'key-special'], 'data': 'Space'},
      {'key': 'alt', 'classes': ['key-square', 'key', 'alt', 'key-special'], 'data': 'AltRight'},
      {'key': '&#706', 'classes': ['key-square', 'key', 'key-special'], 'data': 'ArrowLeft'},
      {'key': '&#709', 'classes': ['key-square', 'key', 'key-special'], 'data': 'ArrowDown'},
      {'key': '&#707', 'classes': ['key-square', 'key', 'key-special'], 'data': 'ArrowRight'},
      {'key': 'ctrl', 'classes': ['key-square', 'key', 'ctrl', 'key-special'], 'data': 'ControlRight'}
    ]
    }
}

export default data;