const data = {
    'en': {
      'keys-row-1': [
        {'key': '`', 'classes': ['key-square', 'key'], 'data': 'Backquote', 'shiftKey': '~'}, 
        {'key': '1', 'classes': ['key-square', 'key'], 'data': 'Digit1', 'shiftKey': '!'}, 
        {'key': '2', 'classes': ['key-square', 'key'], 'data': 'Digit2', 'shiftKey': '@'}, 
        {'key': '3', 'classes': ['key-square', 'key'], 'data': 'Digit3', 'shiftKey': '#'},
        {'key': '4', 'classes': ['key-square', 'key'], 'data': 'Digit4', 'shiftKey': '$'}, 
        {'key': '5', 'classes': ['key-square', 'key'], 'data': 'Digit5', 'shiftKey': '%'}, 
        {'key': '6', 'classes': ['key-square', 'key'], 'data': 'Digit6', 'shiftKey': '^'}, 
        {'key': '7', 'classes': ['key-square', 'key'], 'data': 'Digit7', 'shiftKey': '&'}, 
        {'key': '8', 'classes': ['key-square', 'key'], 'data': 'Digit8', 'shiftKey': '*'}, 
        {'key': '9', 'classes': ['key-square', 'key'], 'data': 'Digit9', 'shiftKey': '('}, 
        {'key': '0', 'classes': ['key-square', 'key'], 'data': 'Digit0', 'shiftKey': ')'}, 
        {'key': '-', 'classes': ['key-square', 'key'], 'data': 'Minus', 'shiftKey': '_'},
        {'key': '=', 'classes': ['key-square', 'key'], 'data': 'Equal', 'shiftKey': '+'},
        {'key': 'backspace', 'classes': ['key-special', 'key', 'backspace'], 'data': 'Backspace', 'shiftKey': 'backspace'},],
    'keys-row-2': [
      {'key': 'tab', 'classes': ['key-special', 'key', 'tab'], 'data': 'Tab', 'shiftKey': 'tab'}, 
      {'key': 'q', 'classes': ['key-square', 'key'], 'data': 'KeyQ', 'shiftKey': 'Q'}, 
      {'key': 'w', 'classes': ['key-square', 'key'], 'data': 'Keyw', 'shiftKey': 'W'}, 
      {'key': 'e', 'classes': ['key-square', 'key'], 'data': 'KeyE', 'shiftKey': 'E'}, 
      {'key': 'r', 'classes': ['key-square', 'key'], 'data': 'KeyR', 'shiftKey': 'R'}, 
      {'key': 't', 'classes': ['key-square', 'key'], 'data': 'KeyT', 'shiftKey': 'T'}, 
      {'key': 'y', 'classes': ['key-square', 'key'], 'data': 'KeyY', 'shiftKey': 'Y'}, 
      {'key': 'u', 'classes': ['key-square', 'key'], 'data': 'KeyU', 'shiftKey': 'U'}, 
      {'key': 'i', 'classes': ['key-square', 'key'], 'data': 'KeyI', 'shiftKey': 'I'}, 
      {'key': 'o', 'classes': ['key-square', 'key'], 'data': 'KeyO', 'shiftKey': 'O'}, 
      {'key': 'p', 'classes': ['key-square', 'key'], 'data': 'KeyP', 'shiftKey': 'P'}, 
      {'key': '[', 'classes': ['key-square', 'key'], 'data': 'BracketLeft', 'shiftKey': '{'},
      {'key': ']', 'classes': ['key-square', 'key'], 'data': 'BracketRight', 'shiftKey': '}'},
      {'key': '&#92;', 'classes': ['key-square', 'key'], 'data': 'Backslash', 'shiftKey': '|'},
      {'key': 'del', 'classes': ['key-special', 'key', 'del'], 'data': 'Delete', 'shiftKey': 'del'},
    ],
    'keys-row-3': [
      {'key': 'capslock', 'classes': ['key-special', 'key', 'capslock'], 'data': 'CapsLock', 'shiftKey': 'capslock'}, 
      {'key': 'a', 'classes': ['key-square', 'key'], 'data': 'KeyA', 'shiftKey': 'A'}, 
      {'key': 's', 'classes': ['key-square', 'key'], 'data': 'KeyS', 'shiftKey': 'S'}, 
      {'key': 'd', 'classes': ['key-square', 'key'], 'data': 'KeyD', 'shiftKey': 'D'}, 
      {'key': 'f', 'classes': ['key-square', 'key'], 'data': 'KeyF', 'shiftKey': 'F'}, 
      {'key': 'g', 'classes': ['key-square', 'key'], 'data': 'KeyG', 'shiftKey': 'G'}, 
      {'key': 'h', 'classes': ['key-square', 'key'], 'data': 'KeyH', 'shiftKey': 'H'}, 
      {'key': 'j', 'classes': ['key-square', 'key'], 'data': 'KeyJ', 'shiftKey': 'J'}, 
      {'key': 'k', 'classes': ['key-square', 'key'], 'data': 'KeyK', 'shiftKey': 'K'}, 
      {'key': 'l', 'classes': ['key-square', 'key'], 'data': 'KeyL', 'shiftKey': 'L'}, 
      {'key': ';', 'classes': ['key-square', 'key'], 'data': 'Semicolon', 'shiftKey': ':'}, 
      {'key': '\'', 'classes': ['key-square', 'key'], 'data': 'Quote', 'shiftKey': '"'},
      {'key': 'enter', 'classes': ['key-special', 'key', 'enter'], 'data': 'Enter', 'shiftKey': 'enter'}, 
    ],
    'keys-row-4': [
      {'key': 'shift', 'classes': ['key-special', 'key', 'shift-1'], 'data': 'ShiftLeft', 'shiftKey': 'shift'}, 
      {'key': 'z', 'classes': ['key-square', 'key'], 'data': 'KeyZ', 'shiftKey': 'Z'}, 
      {'key': 'x', 'classes': ['key-square', 'key'], 'data': 'KeyX', 'shiftKey': 'X'}, 
      {'key': 'c', 'classes': ['key-square', 'key'], 'data': 'KeyC', 'shiftKey': 'C'}, 
      {'key': 'v', 'classes': ['key-square', 'key'], 'data': 'KeyV', 'shiftKey': 'V'}, 
      {'key': 'b', 'classes': ['key-square', 'key'], 'data': 'KeyB', 'shiftKey': 'B'}, 
      {'key': 'n', 'classes': ['key-square', 'key'], 'data': 'KeyN', 'shiftKey': 'N'}, 
      {'key': 'm', 'classes': ['key-square', 'key'], 'data': 'KeyM', 'shiftKey': 'M'}, 
      {'key': ',', 'classes': ['key-square', 'key'], 'data': 'Comma', 'shiftKey': '<'}, 
      {'key': '.', 'classes': ['key-square', 'key'], 'data': 'Period', 'shiftKey': '>'}, 
      {'key': '/', 'classes': ['key-square', 'key'], 'data': 'Slash', 'shiftKey': '?'},
      {'key': '▲', 'classes': ['key-square', 'key', 'key-arrow'], 'data': 'ArrowUp', 'shiftKey': '▲'},
      {'key': 'shift', 'classes': ['key-special', 'key', 'shift-2'], 'data': 'ShiftRight', 'shiftKey': 'shift'}, 
    ],
    'keys-row-5': [
      {'key': 'ctrl', 'classes': ['key-square', 'key', 'ctrl', 'key-special'], 'data': 'ControlLeft', 'shiftKey': 'ctrl'}, 
      {'key': 'win', 'classes': ['key-square', 'key', 'win', 'key-special'], 'data': 'MetaLeft', 'shiftKey': 'win'},
      {'key': 'alt', 'classes': ['key-square', 'key', 'alt', 'key-special'], 'data': 'AltLeft', 'shiftKey': 'alt'},
      {'key': '', 'classes': ['key', 'space', 'key-special'], 'data': 'Space', 'shiftKey': ''},
      {'key': 'alt', 'classes': ['key-square', 'key', 'alt', 'key-special'], 'data': 'AltRight', 'shiftKey': 'alt'},
      {'key': '◄', 'classes': ['key-square', 'key', 'key-arrow'], 'data': 'ArrowLeft', 'shiftKey': '◄'},
      {'key': '▼', 'classes': ['key-square', 'key', 'key-arrow'], 'data': 'ArrowDown', 'shiftKey': '▼'},
      {'key': '►', 'classes': ['key-square', 'key', 'key-arrow'], 'data': 'ArrowRight', 'shiftKey': '►'},
      {'key': 'ctrl', 'classes': ['key-square', 'key', 'ctrl', 'key-special'], 'data': 'ControlRight', 'shiftKey': 'ctrl'}
    ]
    },
    'ru': {
      'keys-row-1': [
        {'key': 'ё', 'classes': ['key-square', 'key'], 'data': 'Backquote', 'shiftKey': 'Ё'}, 
        {'key': '1', 'classes': ['key-square', 'key'], 'data': 'Digit1', 'shiftKey': '!'}, 
        {'key': '2', 'classes': ['key-square', 'key'], 'data': 'Digit2', 'shiftKey': '"'}, 
        {'key': '3', 'classes': ['key-square', 'key'], 'data': 'Digit3', 'shiftKey': '№'}, 
        {'key': '4', 'classes': ['key-square', 'key'], 'data': 'Digit4', 'shiftKey': ';'}, 
        {'key': '5', 'classes': ['key-square', 'key'], 'data': 'Digit5', 'shiftKey': '%'}, 
        {'key': '6', 'classes': ['key-square', 'key'], 'data': 'Digit6', 'shiftKey': ':'}, 
        {'key': '7', 'classes': ['key-square', 'key'], 'data': 'Digit7', 'shiftKey': '?'}, 
        {'key': '8', 'classes': ['key-square', 'key'], 'data': 'Digit8', 'shiftKey': '*'}, 
        {'key': '9', 'classes': ['key-square', 'key'], 'data': 'Digit9', 'shiftKey': '('}, 
        {'key': '0', 'classes': ['key-square', 'key'], 'data': 'Digit0', 'shiftKey': ')'}, 
        {'key': '-', 'classes': ['key-square', 'key'], 'data': 'Minus', 'shiftKey': '_'},
        {'key': '=', 'classes': ['key-square', 'key'], 'data': 'Equal', 'shiftKey': '+'},
        {'key': 'backspace', 'classes': ['key-special', 'key', 'backspace'], 'data': 'Backspace', 'shiftKey': 'backspace'},],
    'keys-row-2': [
      {'key': 'tab', 'classes': ['key-special', 'key', 'tab'], 'data': 'Tab', 'shiftKey': 'tab'}, 
      {'key': 'й', 'classes': ['key-square', 'key'], 'data': 'KeyQ', 'shiftKey': 'Й'}, 
      {'key': 'ц', 'classes': ['key-square', 'key'], 'data': 'Keyw', 'shiftKey': 'Ц'}, 
      {'key': 'у', 'classes': ['key-square', 'key'], 'data': 'KeyE', 'shiftKey': 'У'}, 
      {'key': 'к', 'classes': ['key-square', 'key'], 'data': 'KeyR', 'shiftKey': 'К'}, 
      {'key': 'е', 'classes': ['key-square', 'key'], 'data': 'KeyT', 'shiftKey': 'Е'}, 
      {'key': 'н', 'classes': ['key-square', 'key'], 'data': 'KeyY', 'shiftKey': 'Н'}, 
      {'key': 'г', 'classes': ['key-square', 'key'], 'data': 'KeyU', 'shiftKey': 'Г'}, 
      {'key': 'ш', 'classes': ['key-square', 'key'], 'data': 'KeyI', 'shiftKey': 'Ш'}, 
      {'key': 'щ', 'classes': ['key-square', 'key'], 'data': 'KeyO', 'shiftKey': 'Щ'}, 
      {'key': 'з', 'classes': ['key-square', 'key'], 'data': 'KeyP', 'shiftKey': 'З'}, 
      {'key': 'х', 'classes': ['key-square', 'key'], 'data': 'BracketLeft', 'shiftKey': 'Х'},
      {'key': 'ъ', 'classes': ['key-square', 'key'], 'data': 'BracketRight', 'shiftKey': 'Ъ'},
      {'key': '&#92;', 'classes': ['key-square', 'key'], 'data': 'Backslash', 'shiftKey': '/'},
      {'key': 'del', 'classes': ['key-special', 'key', 'del'], 'data': 'Delete', 'shiftKey': 'del'},
    ],
    'keys-row-3': [
      {'key': 'capslock', 'classes': ['key-special', 'key', 'capslock'], 'data': 'CapsLock', 'shiftKey': 'capslock'}, 
      {'key': 'ф', 'classes': ['key-square', 'key'], 'data': 'KeyA', 'shiftKey': 'Ф'}, 
      {'key': 'ы', 'classes': ['key-square', 'key'], 'data': 'KeyS', 'shiftKey': 'Ы'}, 
      {'key': 'в', 'classes': ['key-square', 'key'], 'data': 'KeyD', 'shiftKey': 'В'}, 
      {'key': 'а', 'classes': ['key-square', 'key'], 'data': 'KeyF', 'shiftKey': 'А'}, 
      {'key': 'п', 'classes': ['key-square', 'key'], 'data': 'KeyG', 'shiftKey': 'П'}, 
      {'key': 'р', 'classes': ['key-square', 'key'], 'data': 'KeyH', 'shiftKey': 'Р'}, 
      {'key': 'о', 'classes': ['key-square', 'key'], 'data': 'KeyJ', 'shiftKey': 'О'}, 
      {'key': 'л', 'classes': ['key-square', 'key'], 'data': 'KeyK', 'shiftKey': 'Л'}, 
      {'key': 'д', 'classes': ['key-square', 'key'], 'data': 'KeyL', 'shiftKey': 'Д'}, 
      {'key': 'ж', 'classes': ['key-square', 'key'], 'data': 'Semicolon', 'shiftKey': 'Ж'}, 
      {'key': 'э', 'classes': ['key-square', 'key'], 'data': 'Quote', 'shiftKey': 'Э'},
      {'key': 'enter', 'classes': ['key-special', 'key', 'enter'], 'data': 'Enter', 'shiftKey': 'enter'}, 
    ],
    'keys-row-4': [
      {'key': 'shift', 'classes': ['key-special', 'key', 'shift-1'], 'data': 'ShiftLeft', 'shiftKey': 'shift'}, 
      {'key': 'я', 'classes': ['key-square', 'key'], 'data': 'KeyZ', 'shiftKey': 'Я'}, 
      {'key': 'ч', 'classes': ['key-square', 'key'], 'data': 'KeyX', 'shiftKey': 'Ч'}, 
      {'key': 'с', 'classes': ['key-square', 'key'], 'data': 'KeyC', 'shiftKey': 'С'}, 
      {'key': 'м', 'classes': ['key-square', 'key'], 'data': 'KeyV', 'shiftKey': 'М'}, 
      {'key': 'и', 'classes': ['key-square', 'key'], 'data': 'KeyB', 'shiftKey': 'И'}, 
      {'key': 'т', 'classes': ['key-square', 'key'], 'data': 'KeyN', 'shiftKey': 'Т'}, 
      {'key': 'ь', 'classes': ['key-square', 'key'], 'data': 'KeyM', 'shiftKey': 'Ь'}, 
      {'key': 'б', 'classes': ['key-square', 'key'], 'data': 'Comma', 'shiftKey': 'Б'}, 
      {'key': 'ю', 'classes': ['key-square', 'key'], 'data': 'Period', 'shiftKey': 'Ю'}, 
      {'key': '.', 'classes': ['key-square', 'key'], 'data': 'Slash', 'shiftKey': ','},
      {'key': '▲', 'classes': ['key-square', 'key', 'key-arrow'], 'data': 'ArrowUp', 'shiftKey': '▲'},
      {'key': 'shift', 'classes': ['key-special', 'key', 'shift-2'], 'data': 'ShiftRight', 'shiftKey': 'shift'}, 
    ],
    'keys-row-5': [
      {'key': 'ctrl', 'classes': ['key-square', 'key', 'ctrl', 'key-special'], 'data': 'ControlLeft', 'shiftKey': 'ctrl'}, 
      {'key': 'win', 'classes': ['key-square', 'key', 'win', 'key-special'], 'data': 'MetaLeft', 'shiftKey': 'win'},
      {'key': 'alt', 'classes': ['key-square', 'key', 'alt', 'key-special'], 'data': 'AltLeft', 'shiftKey': 'alt'},
      {'key': '', 'classes': ['key', 'space', 'key-special'], 'data': 'Space', 'shiftKey': ''},
      {'key': 'alt', 'classes': ['key-square', 'key', 'alt', 'key-special'], 'data': 'AltRight', 'shiftKey': 'alt'},
      {'key': '◄', 'classes': ['key-square', 'key', 'key-arrow'], 'data': 'ArrowLeft', 'shiftKey': '◄'},
      {'key': '▼', 'classes': ['key-square', 'key', 'key-arrow'], 'data': 'ArrowDown', 'shiftKey': '▼'},
      {'key': '►', 'classes': ['key-square', 'key', 'key-arrow'], 'data': 'ArrowRight', 'shiftKey': '►'},
      {'key': 'ctrl', 'classes': ['key-square', 'key', 'ctrl', 'key-special'], 'data': 'ControlRight', 'shiftKey': 'ctrl'}
    ]
    }
}

export default data;